DROP TABLE IF EXISTS computer CASCADE;

DROP TABLE IF EXISTS human CASCADE;

DROP TABLE IF EXISTS lightning_strikes CASCADE;

DROP TABLE IF EXISTS router CASCADE;

DROP TABLE IF EXISTS web CASCADE;

DROP TABLE IF EXISTS ram_info CASCADE;